# Generated by Django 6.0.5 on 2026-05-27 11:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0026_add_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryTaskLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_name', models.CharField(db_index=True, max_length=255)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('STARTED', 'Started'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], db_index=True, default='STARTED', max_length=16)),
                ('email_status', models.CharField(choices=[('NONE', 'None'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('PARTIAL', 'Partial')], default='NONE', max_length=16)),
                ('email_sent_count', models.PositiveIntegerField(default=0)),
                ('email_failed_count', models.PositiveIntegerField(default=0)),
                ('message', models.TextField(blank=True, default='')),
                ('details', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Celery Task Log',
                'verbose_name_plural': 'Celery Task Logs',
                'db_table': 'celery_task_log',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['task_name', 'status'], name='celery_task_task_na_411c2e_idx'), models.Index(fields=['celery_task_id'], name='celery_task_celery__9b117d_idx'), models.Index(fields=['-started_at'], name='celery_task_started_e52fdd_idx')],
            },
        ),
    ]
